#!/bin/bash -eu

cd $(dirname $0)/..

export ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
export SERVICE_NAME=${SERVICE_NAME:-youtube-downloader-bot-telegram}
export SERVICE_SA=${SERVICE_SA:-197169329270-compute@developer.gserviceaccount.com}
export GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-luthfi-project-367206}
export DEPLOY_REGION=${DEPLOY_REGION:-us-central1}
export IMAGE_NAME=gcr.io/${GOOGLE_CLOUD_PROJECT}/${SERVICE_NAME}
export IMAGE_VERSION=$(echo ${TAG_NAME} | sed 's/v//')
export REVISION_SUFFIX=$(echo ${IMAGE_VERSION} | sed 'y/./-/')

# Django env
export DEBUG=${DEBUG:-False}
export BOT_TOKEN=${BOT_TOKEN}