#!/bin/bash -eu

cd $(dirname $0)/..

source ./auto/config

gcloud run deploy $SERVICE_NAME \
    --image $IMAGE_NAME:$IMAGE_VERSION \
    --region $DEPLOY_REGION \
    --platform managed \
    --memory 512Mi \
    --cpu 1 \
    --concurrency 80 \
    --allow-unauthenticated \
    --service-account $SERVICE_ACCOUNT \
    --set-env-vars DEBUG=$DEBUG,ALLOWED_HOSTS=$ALLOWED_HOSTS,BOT_TOKEN=$BOT_TOKEN,BOT_USERNAME=$BOT_USERNAME,URL=$URL \
    --revision-suffix $REVISION_SUFFIX