#!/bin/bash -eu

cd $(dirname $0)/..

source ./auto/config

# Build docker image
docker build \
-t $IMAGE_NAME:$IMAGE_VERSION \
-t $IMAGE_NAME:latest \
.

# Push to image registy
docker push $IMAGE_NAME:$IMAGE_VERSION
docker push $IMAGE_NAME:latest